### ISSUE TITLE
Alignment fix

### ISSUE THREAD

**Issue by fox8091** [phijor/SpecializeMii#1]
I noticed that in mii.h, you mentioned compiler specific alignment on structs. Well, here's some things that may help:

`__attribute__((aligned (8)));`
`__attribute__ ((packed));`

**Comment by phijor** [comment]
Thank you for the information.

Until now the compiler was rather compliant with my request to interpret binary data by overlaying `struct`s, but if I'd ever run into trouble I might add these attributes. The code can't get any less portable anyway (which it is not intended to be).

Right now I'm [statically checking for the correct offsets](https://github.com/phijor/SpecializeMii/blob/b52ff430de1e643c49f6a30c06d27540fb3e52d9/src/mii.h#L107-L120). If somehow, the compiler decides to randomly add padding/extra alignment, I'll know.

If you don't mind, I'll close this issue, but encourage you to suggest further enhancements :+1:

PS: Aren't you also developing corbenik CFW? This is a small world.

**Comment by fox8091** [comment]
Feel free to close. And umm..sorta. I started work on a new patch. But yea, people get around. ;)
