### ISSUE TITLE
Confirmation on specializing Personal Mii goes away too quickly

### ISSUE THREAD

**Issue by XT-8147** [phijor/SpecializeMii#3]
The confirmation on specializing the Personal Mii checks to see if I'm pressing A while I still have A pressed originally, from trying to make it special.  The confirmation ever so briefly flashes up on screen before going away (since pressing A confirms it).  I can get the confirmation to stay on screen by very quickly pressing and releasing A, but ideally the confirmation should either wait for the A button to be released and re-pressed, or use a different button.

**Comment by phijor** [comment]
This should be fixed with f2cfc9e. I don't really know what caused it but I know that *not running a busy-loop* really seems to avoid many problems.

Thanks again for reporting; I will close this issue. If the issue persists, just comment and I will re-open.
